language: ruby
rvm:
  - 2.4.1

env:
  global:
    - CC_TEST_REPORTER_ID=c520a078d49537a2f88189fb8096cce8e6437b852f4435df2381d68e996963d0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec
  - bundle exec cucumber features

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# before_install:
#   - nvm install                         # Install node version from .nvmrc
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter

# install:
#   - bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}  # Install ruby gems, excluding production only gems such as unicorn (already present by default in Travis)
#   - npm install                         # Install npm dependencies

# before_script:
#   - ./cc-test-reporter before-build
#   - bundle exec rake db:create db:migrate

# script:
#   - bundle exec rspec
#   - bundle exec cucumber features

# after_script:
#   - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json # Format backend coverage
#   - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/frontend/lcov.info  # Format frontend coverage
#   - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
#   - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json